apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thelounge
  strategy:
    type: Recreate
  template:
    metadata:
      name: thelounge
      labels:
        app: thelounge
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: thelounge
        image: thelounge/thelounge:latest
        env:
        - name: THELOUNGE_HOME
          value: /var/lib/thelounge/data
        volumeMounts:
        - mountPath: /var/lib/thelounge
          name: data
        ports:
        - name: http
          containerPort: 9000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: thelounge-data
